-- Migration generated by Drizzle ORM
-- Database: PostgreSQL
-- Created: 2026-08-17

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "users" (
  "clerk_user_id" text PRIMARY KEY NOT NULL,
  "email" text NOT NULL UNIQUE,
  "display_name" text NOT NULL,
  "avatar_url" text,
  "concurso_id" text,
  "daily_goal_minutes" integer DEFAULT 30,
  "xp_total" integer DEFAULT 0,
  "current_rank" integer DEFAULT 0,
  "current_streak" integer DEFAULT 0,
  "max_streak" integer DEFAULT 0,
  "is_premium" boolean DEFAULT false,
  "premium_expires_at" timestamp,
  "stripe_customer_id" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "last_activity_at" timestamp
);

-- ============================================
-- REFERENCE DATA TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS "concursos" (
  "id" text PRIMARY KEY NOT NULL,
  "nome" text NOT NULL UNIQUE,
  "categoria" text NOT NULL CHECK ("categoria" IN ('militares', 'policiais', 'bancarios', 'fiscais', 'tribunais', 'administrativos', 'saude')),
  "descricao" text,
  "instituicao" text NOT NULL,
  "ativo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "materias" (
  "id" text PRIMARY KEY NOT NULL,
  "nome" text NOT NULL UNIQUE,
  "slug" text NOT NULL UNIQUE,
  "descricao" text,
  "icon_name" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "bancas" (
  "id" text PRIMARY KEY NOT NULL,
  "nome" text NOT NULL UNIQUE,
  "sigla" text NOT NULL UNIQUE,
  "descricao" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- QUESTIONS & ANSWERS TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS "questions" (
  "id" text PRIMARY KEY NOT NULL,
  "concurso_id" text NOT NULL,
  "materia_id" text NOT NULL,
  "banca_id" text NOT NULL,
  "enunciado" text NOT NULL,
  "alternatives" jsonb NOT NULL,
  "correct_alternative_id" text NOT NULL,
  "explanation" text,
  "alternative_explanations" jsonb,
  "dificuldade" text DEFAULT 'medio' CHECK ("dificuldade" IN ('facil', 'medio', 'dificil')),
  "year" integer,
  "image_url" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("concurso_id") REFERENCES "concursos"("id"),
  FOREIGN KEY ("materia_id") REFERENCES "materias"("id"),
  FOREIGN KEY ("banca_id") REFERENCES "bancas"("id")
);

CREATE TABLE IF NOT EXISTS "user_answers" (
  "id" text PRIMARY KEY NOT NULL,
  "clerk_user_id" text NOT NULL,
  "question_id" text NOT NULL,
  "selected_alternative_id" text NOT NULL,
  "is_correct" boolean NOT NULL,
  "time_spent_seconds" integer,
  "source" text DEFAULT 'practice' CHECK ("source" IN ('practice', 'simulado', 'duel')),
  "source_id" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("clerk_user_id") REFERENCES "users"("clerk_user_id"),
  FOREIGN KEY ("question_id") REFERENCES "questions"("id")
);

-- ============================================
-- SIMULADO TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS "simulados" (
  "id" text PRIMARY KEY NOT NULL,
  "clerk_user_id" text NOT NULL,
  "concurso_id" text NOT NULL,
  "format" text DEFAULT 'completo' CHECK ("format" IN ('completo', 'por_materia', 'tempo_real', 'customizado')),
  "total_questions" integer NOT NULL,
  "correct_answers" integer DEFAULT 0,
  "time_spent_seconds" integer DEFAULT 0,
  "started_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "completed_at" timestamp,
  "score" integer DEFAULT 0,
  "percentile" integer,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("clerk_user_id") REFERENCES "users"("clerk_user_id"),
  FOREIGN KEY ("concurso_id") REFERENCES "concursos"("id")
);

CREATE TABLE IF NOT EXISTS "simulado_questions" (
  "id" text PRIMARY KEY NOT NULL,
  "simulado_id" text NOT NULL,
  "question_id" text NOT NULL,
  "order_index" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("simulado_id") REFERENCES "simulados"("id"),
  FOREIGN KEY ("question_id") REFERENCES "questions"("id")
);

-- ============================================
-- DUEL TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS "duels" (
  "id" text PRIMARY KEY NOT NULL,
  "player1_id" text NOT NULL,
  "player2_id" text NOT NULL,
  "mode" text DEFAULT 'random' CHECK ("mode" IN ('random', 'materia_specific', 'ranked')),
  "total_questions" integer DEFAULT 10,
  "player1_score" integer DEFAULT 0,
  "player2_score" integer DEFAULT 0,
  "winner_id" text,
  "started_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "completed_at" timestamp,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("player1_id") REFERENCES "users"("clerk_user_id"),
  FOREIGN KEY ("player2_id") REFERENCES "users"("clerk_user_id"),
  FOREIGN KEY ("winner_id") REFERENCES "users"("clerk_user_id")
);

-- ============================================
-- ACHIEVEMENTS TABLES
-- ============================================
CREATE TABLE IF NOT EXISTS "achievements" (
  "id" text PRIMARY KEY NOT NULL,
  "nome" text NOT NULL UNIQUE,
  "descricao" text,
  "icon_name" text,
  "condicao" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "user_achievements" (
  "id" text PRIMARY KEY NOT NULL,
  "clerk_user_id" text NOT NULL,
  "achievement_id" text NOT NULL,
  "unlocked_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("clerk_user_id") REFERENCES "users"("clerk_user_id"),
  FOREIGN KEY ("achievement_id") REFERENCES "achievements"("id")
);

-- ============================================
-- USER STATS TABLE (cached for performance)
-- ============================================
CREATE TABLE IF NOT EXISTS "user_stats" (
  "clerk_user_id" text PRIMARY KEY NOT NULL,
  "total_questions_answered" integer DEFAULT 0,
  "total_correct" integer DEFAULT 0,
  "total_incorrect" integer DEFAULT 0,
  "overall_accuracy" integer DEFAULT 0,
  "total_study_time_seconds" integer DEFAULT 0,
  "this_week_study_time_seconds" integer DEFAULT 0,
  "last_study_date" timestamp,
  "best_streak" integer DEFAULT 0,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("clerk_user_id") REFERENCES "users"("clerk_user_id")
);

-- ============================================
-- STUDY LOGS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "study_logs" (
  "id" text PRIMARY KEY NOT NULL,
  "clerk_user_id" text NOT NULL,
  "materia_id" text NOT NULL,
  "duration_seconds" integer NOT NULL,
  "questions_answered" integer DEFAULT 0,
  "correct_answers" integer DEFAULT 0,
  "session_type" text DEFAULT 'free_practice' CHECK ("session_type" IN ('free_practice', 'timed', 'simulado')),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("clerk_user_id") REFERENCES "users"("clerk_user_id"),
  FOREIGN KEY ("materia_id") REFERENCES "materias"("id")
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users"("email");
CREATE INDEX IF NOT EXISTS "idx_users_clerk_id" ON "users"("clerk_user_id");
CREATE INDEX IF NOT EXISTS "idx_questions_concurso" ON "questions"("concurso_id");
CREATE INDEX IF NOT EXISTS "idx_questions_materia" ON "questions"("materia_id");
CREATE INDEX IF NOT EXISTS "idx_user_answers_user" ON "user_answers"("clerk_user_id");
CREATE INDEX IF NOT EXISTS "idx_user_answers_question" ON "user_answers"("question_id");
CREATE INDEX IF NOT EXISTS "idx_simulados_user" ON "simulados"("clerk_user_id");
CREATE INDEX IF NOT EXISTS "idx_simulados_concurso" ON "simulados"("concurso_id");
CREATE INDEX IF NOT EXISTS "idx_study_logs_user" ON "study_logs"("clerk_user_id");
CREATE INDEX IF NOT EXISTS "idx_duels_player1" ON "duels"("player1_id");
CREATE INDEX IF NOT EXISTS "idx_duels_player2" ON "duels"("player2_id");

-- ============================================
-- DRIZZLE MIGRATIONS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS "__drizzle_migrations__" (
  "id" SERIAL PRIMARY KEY,
  "hash" text NOT NULL UNIQUE,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Record this migration
INSERT INTO "__drizzle_migrations__" ("hash", "created_at")
VALUES ('0001_create_ia_aprova_schema', CURRENT_TIMESTAMP)
ON CONFLICT ("hash") DO NOTHING;
