const colors = {
  light: {
    primary: '#1D5DFF',
    primaryDark: '#0E2F7A',
    primaryLight: '#EEF3FF',
    success: '#22C55E',
    xpOrange: '#F59E0B',
    error: '#EF4444',
    background: '#F8FAFC',
    white: '#FFFFFF',
    card: '#FFFFFF',
    text: '#0F172A',
    textSecondary: '#64748B',
    textLight: '#94A3B8',
    border: '#E2E8F0',
    muted: '#F1F5F9',
    tint: '#1D5DFF',
    foreground: '#0F172A',
    cardForeground: '#0F172A',
    primaryForeground: '#FFFFFF',
    secondary: '#F1F5F9',
    secondaryForeground: '#0F172A',
    muted2: '#F1F5F9',
    mutedForeground: '#94A3B8',
    accent: '#EEF3FF',
    accentForeground: '#1D5DFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    input: '#E2E8F0',
  },
  radius: 24,
};

export default colors;
